<?php

/**
 * Implements hook_theme().
 */
function guestbook_theme($existing, $type, $theme, $path)
{
  return [
    "guest_book_form"=>[
      'template' => 'guest-book-form',
      "variables"=>[
        'form' => [],
        'table' => [],
        'guest_book_list' => [],
      ]
    ],
    "guest_book_list"=>[
      'template' => 'guest-book-list',
      "variables" => [
        'name' => null,
        'email' => null,
        'phone_number' => null,
        'response' => null,
        'avatar' => null,
        'image' => null,
        'timestamp' => null,
        'id' => null,
      ]
    ],
  ];
}
